IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'icUrlTracker')
BEGIN
    ALTER TABLE [icUrlTracker] ALTER COLUMN OldUrl NVARCHAR(1000)
    ALTER TABLE [icUrlTracker] ALTER COLUMN OldUrlQueryString NVARCHAR(1000)
    ALTER TABLE [icUrlTracker] ALTER COLUMN OldRegex NVARCHAR(1000)
    ALTER TABLE [icUrlTracker] ALTER COLUMN RedirectUrl NVARCHAR(1000)
    ALTER TABLE [icUrlTracker] ALTER COLUMN Notes NVARCHAR(1000)
    ALTER TABLE [icUrlTracker] ALTER COLUMN Referrer NVARCHAR(1000)
END